language: node_js

node_js:
    - '6.0.0'

notifications:
    email: false

cache:
  directories:
    - $HOME/.npm

before_script:
    # Install packages. npm install is run by default for node_js language type.
    - npm install -g bower grunt-cli
    - npm install

script:
    - grunt test
